services:
    postgres-db:
        image: postgres:17
        ports:
            - "5433:5432"
        environment:
            - POSTGRES_DB=proexpense
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=root

    spring-app:
        image: proexpense-backend:latest
        ports:
            - "8080:8080"
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/proexpense
        depends_on:
            -   postgres-db

    spa-app:
        build:
            context: ./ProExpense-frontend
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        depends_on:
            -   spring-app
